apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sss
  name: sss
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sss
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sss
    spec:
      containers:
      - image: u20041-kworker3-dev:5000/sss:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: sss
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
