apiVersion: v1
kind: Service
metadata:
  labels:
    app: sss
  name: sss
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30825
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sss
  sessionAffinity: None
  type: LoadBalancer
