apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app-ws
  name: my-app-ws
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-ws
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-app-ws
    spec:
      containers:
      - image: u20041-kworker3-dev:5000/my-app-ws:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: my-app-ws
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
